---
folder_path: experiment
logger:
  level: 10 # CRITICAL = 50, ERROR = 40, WARNING = 30, INFO = 20, DEBUG = 10, NOTSET = 0
  format: "%(asctime)s - %(levelname)s - %(message)s"
seed: 42
epochs: 2
batch_size: 512
learning_rate: 0.001
model_units: 32
model_layers: 3
model_dropout: 0.5
dataset: ogbg-molfreesolv #JA: ogbg-molesol, ogbg-molfreesolv, ogbg-mollipo, ZINC
mode: my_attention # default, fc_weight, fc_extra, gat_attention, nagsl_attention, my_attention
bidirectional: True
new_grap_edge_value:
  - 0
  - 0
  - 0
data_name: attention_edge_weight