---
folder_path: experiment
seed: 42
epochs: 10
batch_size: 32
learning_rate: 0.001
network: general_gnn
dataset: ogbg-molhiv
train_test_split: 0.8
hidden_layers: 4
convolution_neurons: 128
pairwise: 1













