---
folder_path: experiment
seed: 42
epochs: 10
batch_size: 32
learning_rate: 0.001
model: prgnn # general_gnn, direct_ranker, prgnn
dataset: ogbg-mollipo #JA: QM9, ogbg-molesol, molfreesolv, ogbg-mollipo, ZINC| NEIN: aspirin
train_test_split: 0.8
hidden_layers: 4
convolution_neurons: 128
pairwise: 1