---
folder_path: experiment
logger:
  level: 10 # CRITICAL = 50, ERROR = 40, WARNING = 30, INFO = 20, DEBUG = 10, NOTSET = 0
  format: "%(asctime)s - %(levelname)s - %(message)s"
seed: 44
logging_inverval: 5
epochs: 201
batch_size: 512
learning_rate: 0.001
model_units: 32
model_units2: 32
model_layers: 2
model_dropout: 0.5
dataset: ogbg-molfreesolv
mode: fc
attention: self
bidirectional: True
new_grap_edge_value:
  - 0
  - 0
  - 0
data_name: data_name